WIP: Add avatar component
Elonsoft/elonkit pull request #41
Opened 2020-09-09 15:52 UTC by klimenkosergei

2020-09-21 14:36 UTC, feerzlay requested changes

2020-09-21 14:36 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get width(): number {
Нужно ли нам два отдельных инпута под размер, или может просто один `size` сделать?

2020-09-21 14:36 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get statusWidth(): number {
А компонент бейджа случайно не сделает эту фичу со статусом?

2020-09-21 14:36 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.html
> +    [alt]="(locale$ | async).avatar.labelAvatar"
Это надо произвольным текстом через инпут делать

2020-09-21 14:36 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get icon(): ESAvatarIcon {
Не уверен что этому компоненту так уже сильно нужны встроенные иконки. Может сделать как в material-ui, плейсхолдер через ng-content прокидывать? Там может хоть иконка, хоть текст быть. А само изображение тогда просто через `src`.

2020-09-21 14:36 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-basic/avatar-story-basic.component.html
> +<es-avatar
Неплохо бы в демке дать возможность ссылку на изображение указывать

2021-01-15 07:05 UTC, evseevdev commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get width(): number {
Аватар может быть не квадратным? Если он только квадратный, то можно сделать один size.

2021-02-18 14:55 UTC, feerzlay requested changes

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public defaultIconSrc?: string;
Еще в прошлом ревью писал, что дефолтная иконка этому компоненту не нужна. Если кому-то так сильно это понадобится, то он может компонент-обертку сделать, например.

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public avatarSrc?: string;
Просто `src`

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input()
Этот инпут уже лишним будет, когда уберем икноку по умолчанию.

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Output() public clickEvent = new EventEmitter();
Родитель может сделать `<es-avatar (click)="onClick()">`, этот output тут лишний.

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public altText?: string;
Просто `alt`

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.types.ts
> +  altText?: string;
Странно иметь значения по умолчанию для `src` и `alt`

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get formType(): ESAvatarForm {
Давай лучше `variant` назовем.

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +   * Defines using round or square avatar.
The shape of the avatar.

2021-02-18 14:55 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.scss
> +  &__status {
Если этот бейдж это просто кружок сверху без всяких масок, то нет смысла перегружать им компонент аватара, как по мне. И nтогда просто вынести его в отдельный компонент `badge`.

2021-02-18 16:11 UTC, AndreyMorozow commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public avatarSrc?: string;
Уже есть геттер scr, да и для единообразия со statusSrc

2021-02-18 16:22 UTC, AndreyMorozow commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input()
Так а как тогда проверять текстовые аватары? src всегда что-то возвращает, если не прокинуть свою иконку, то вернет дефолтную

2021-02-25 15:58 UTC, feerzlay requested changes

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/components/avatar-group/avatar-group.module.ts
> +import { ESAvatarGroupComponent } from './avatar-group.component';
Этот компонент можно в модуль аватара добавить и не заводить отдельный

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/components/avatar-group/avatar-group.component.html
> +  <es-avatar
Аватары надо через `ng-content` передавать

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/components/avatar-group/avatar-group.component.scss
> +.group {
`.es-avatar-group`

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/components/avatar-group/avatar-group.component.ts
> +import {
Этот компонент можно положить на один уровень с `avatar-component.ts`

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/locale/locales/ru.ts
> +  avatar: {
Локали не используются, убрать

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/assets/elonkit/avatar/seal.svg
> +<svg width="40" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M28.39 27.37L24.38 26 23 30l-3.08-6L17 30l-1.38-4-4.01 1.37 2.92-6a7 7 0 1110.94 0l2.92 6zM15 17l2.69 1.34-.19 3 2.
Эти иконки же уже не используются? Да и не должны в любом случае)
Если нужны будут для демки в сторибуке то их надо перенести в соответствующую папку

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-actions/avatar-story-actions.source.ts
> +export const AVATAR_STORY_ACTIONS_SOURCE = {
Кстати а в чем смысл этой демки? Похоже просто на копипасту)
Все таки аватар обычно не предназначен для какого-то взаимодействия с ним и делать демку на эту тему не нужно

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-custom/avatar-story-custom.component.html
> +<es-avatar
Это чем-то отличается от basic?

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.theme.scss
> +  $cl-text: map-get($elonkit-theme, mono-a);
Дважды один и тот же извлекается, просто сделать один `$cl-mono-a`

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.theme.scss
> +  $cl-default: map-get($elonkit-theme, mono-b);
`$cl-mono-b`

2021-02-25 15:58 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get borderRadius(): number {
Сейчас задумался нужен ли инпут для этого
Можно просто сделать в стилях модификаторы `_variant_square` и  `_variant_round`, в квадратном просто значение из дизайна взять. А если на проекте нужны другие сгругления то всегда можно перезатереть.

2021-03-03 10:52 UTC, feerzlay requested changes

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.scss
> +    border-radius: 5px;
А в дизайне он 8

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public avatarSrc?: string;
Остался старый инпут

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +    this._textTypography = value || 'mat-body-2';
Значение по умолчанию надо из нашей типографики брать

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public locale$: Observable<ESLocale>;
Лишнее

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.types.ts
> +export enum ESAvatarForm {
`ESAvatarVariant`, чтобы с названием инпута совпадало

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.theme.scss
> +    &__status {
Лишнее

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/avatar-story-group.component.scss
> +.typography {
Вообще типографику можно не переопределять в демках, достаточно описания апи компонента

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/avatar-story-group.component.html
> +    [ngStyle]="{ 'z-index': avatars.length - i }"
Можно ли это автоматизировать? В реактовском material-ui это как-то делается

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
> +    expect(component.fixture.componentInstance.variant).toBe('round');
Лучше это проверять через `toHaveClass`. А то выходит в духе
```
const foo = 5;
expect(foo).toBe(5);
```

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-basic/avatar-story-basic.component.ts
> +export class AvatarStoryBasicComponent {
Можно не создавать обертку для демки, если она просто инпуты прокидывает
Просто прям с mdx файле прописать template

2021-03-03 10:52 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +## Demos
По хорошему нам нужны следующие демки:
- с изображением 
- без изображения с иконкой (иконки можно борать из иконочного шрифта)
- без изображения с текстом 
- `avatar-group`

2021-03-05 07:09 UTC, feerzlay requested changes

2021-03-05 07:09 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.ts
> +  public ngAfterContentInit() {
Тут проблема что они высчитываются только раз. Если мы динамически изменим сожержимое то все сломается. У `QueryList` вроде есть какое-то поле на которое можно подписаться чтобы следить за изменениями

2021-03-05 07:09 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.ts
> +    this.avatars.forEach((avatar, i) => (avatar.nativeElement.style.zIndex = i));
Менять аттрибуты лучше через `renderer2`

2021-03-10 08:59 UTC, feerzlay requested changes

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +      component: AvatarStoryNoImageTypographyComponent,
Давай его тоже через template, пофиг на textTypography
Тем более что мы показываем как оно по дефолту выглядит

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.scss
> +  &__text {
Не используется уже?

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  @Input() public text?: string;
Лишнее

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public get textTypography(): string {
Так как это единственная типографика, то давай просто typography сделаем. И во всяких defaultOptions соответственно тоже позаменять.

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +   * Src for avatar image
`The src attribute for avatar image.`
И да, я стараюсь везде точки ставить в доках)

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +   * Text fro alt attribute
Очепятка и можно покрасивее перефразировать
`The alt attribute for avatar image.`

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +   * Defines size of the avatar in pixels.
Просто `Size of the avatar in pixels.`

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/storybook/assets/icons/avatar/star.svg
> +<svg width="10" height="9" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.244 1.174c.25-.717 1.263-.717 1.512 0l.472 1.359a.8.8 0 00.74.537l1.437.029c.759.015 1.072.98.467 1.437l-1.146.87
Это же нигде не используется, можно удалить?

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
> +@Component({
Не используется?

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
> +    expect(component.fixture.componentInstance.size).toBe(200);
Дубль

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
> +  it('Should render alt text on image', async () => {
`Should render image with alt text`

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
> +  it('Should render text on input', async () => {
`Should render text avatar`

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +          <mat-icon>thumb_up</mat-icon>
Сюда бы иконку account или как она там называется, чтобы ближе к реальности было

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +      component: AvatarStoryGroupComponent,
Да и эту демку можно прям тут захардкодить, без цикла даже нагляднее будет

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +      size: 40,
Общие контролы (variant, size) можно в meta вынести, чтобы не дублировать

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  public avatarForm = ESAvatarVariant;
Попал в доки, нужно игнор добавить
И заодно можно в `avatarVariant` переименовать

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +      alt: 'alt text',
Elonsoft

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +`alt` - text for alt attribute;
Давай помогу :D
Вот это все начиная от подзаголовка (включительно) заменяем на
```
We can create image avatars by passing `src` input to the component.
```

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +`textTypography` - css class for passing text;
А тут просто убрать описание, будут рядом стоять думки иконки и текста

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +Are created by passing mat-icon via ng-content instead of src input
When `src` input is missing or falsy, content is used instead. Icon or text can be used for a content.

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +Are created by looping of avatars components
We can use avatar group to render avatars as a stack.

2021-03-10 08:59 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +<ArgsTable of={ESAvatarComponent} />
Раз у нас два компонента, то можно добавить таблицу и для AvatarGroup, только сделать подзаголовки к ним

2021-03-23 14:51 UTC, feerzlay requested changes

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.ts
> +  private _size: number;
Это уже связано с приколами сборки о которых недавно узнал. Надо его как `any` затипизировать, иначе ангуляр будет ругаться что не может string к number привести.

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +Are created by passing typography via ng-content instead of src input.
В прошлый раз имел в виду не только описание инпутов, но и заголовок с текстом удалить для текстовых аватаров. Все что нужно уже описано выше, а тут просто две демки подряд. Кстати заголовки Image Avatars, Icon Avatars и Group avatars тоже стоит удалить, чтобы с другими доками единообразно было.

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.scss
> +  &__avatar {
Что-то не обратил внимания раньше - мы же можем селект просто по `.es-avatar` делать и тогда на них не нужно будет классы добавлять.

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.scss
> +    border: 2px solid #fff;
Тут белый лучше не хардкодить, а брать из темы,  чтобы в темной на черный переключался

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +      typography: 'typography'
Тут пустое начальное значение сделать

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +`size` - size of all avatars in group;
Лишнее, есть в описании апи ниже
И пустой заголовок сверху подчистить)

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
> +### Avatar group component
Давай заголовки как компоненты сделаем, ESAvatarComponent и ESAvatarGroupComponent

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/avatar-story-group.source.ts
> +export const AVATAR_STORY_GROUP_SOURCE = {
Подчисти из историй все файлы компонентов, уже же в template вынесли
И source файлы надо бы обновить

2021-03-23 14:51 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-icon/index.ts
> +export { AVATAR_STORY_NO_IMAGE_ICON_SOURCE } from './avatr-story-no-image-icon.source';
Очепятка, `avatr`

2021-03-25 07:53 UTC, feerzlay requested changes

2021-03-25 07:53 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.scss
> +  .es-avatar-group__avatar {
Тут забыл поменять

2021-03-25 07:53 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar.component.theme.scss
> +    border: 2px solid mat-color($cl-mono-b, 500);
Это так понимаю из avatar-group пришло? 
Все же оно должно только для аватаров в группе применяться, а не для всех. Просто сделай файл `avatar-group.component.theme.scss` и здесь его потом импортнуть (для примера - хлебные крошки)

2021-03-25 07:53 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/avatar-story-group.source.ts
> +  ts: `
В целом ts часть можно убрать, но в описании компонента дописать что "Size input of avatar group and nested avatars must match."

2021-03-29 07:19 UTC, feerzlay requested changes

2021-03-29 07:19 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/avatar-group.component.theme.scss
> +  .es-avatar {
Оно все еще применяется к аватарам вне группы :)

2021-03-29 07:19 UTC, feerzlay commented on projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-typography/avatar-story-no-image-typography.source.ts
> +  scss: `
Заодно вот тут стили и typography убрать из демки

2021-03-31 15:08 UTC, merged